config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  get '/items/detail_search', to: 'items#detail_search', as: 'detail_search_items'
  get '/items/detail_search_result', to: 'items#detail_search_result', as: 'detail_search_result_items'
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :address_lists, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :items, only: [:index, :show] do
    collection do
      get 'search'
      get 'searchResult'
    end
    resources :favorite_item, only: [:create, :destroy]
  end
  resources :carts, only: [:index, :create, :update, :destroy]
  resources :orders, only: [:index, :new, :create]
end

app/models/address_list.rb
class AddressList < ApplicationRecord
  belongs_to :user
  has_many   :orders
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :items
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :item_list
  has_many   :items, through: :item_lists

  # accepts_nested_attributes_for :cart_records

  def self.total_price(carts)
    total_price = 0
    carts.each do |cart|
      total_price += cart.item_list.item.proposed_price
    end
    return total_price
  end

  def self.add_order_items_and_destory_carts(carts, ordered_history_id)
    carts.each {|cart|
      OrderedItem.create!(order_history_id: ordered_history_id, item_id: cart.item_list.item_id, color_id: cart.item_list.color_id, size_id: cart.item_list.size_id, quantity: cart.quantity, regular_price: cart.item_list.item.regular_price, item_name: cart.item_list.item.name, shop_name: cart.item_list.item.shop.name, color_name: cart.item_list.color[:color], size_name: cart.item_list.size[:size])
      cart.destroy!
    }
  end
end

app/models/cart_record.rb
class CartRecord < ApplicationRecord
  belongs_to :user
  belongs_to :item_list
  has_many   :items, through: :item_lists
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :carts
  has_many :items, through: :item_lists
  has_many :item_lists
  has_many :sub_images
  has_many :ordered_items
end

app/models/demension.rb
class Demension < ApplicationRecord
  belongs_to :item_list
  belongs_to :size
end

app/models/favorite_item.rb
class FavoriteItem < ApplicationRecord
  belongs_to :user
  belongs_to :item, optional: true
end

app/models/gender.rb
class Gender < ApplicationRecord
  has_many :items
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :color
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :colors, through: :item_lists
  has_many :sizes, through: :item_lists
  has_many :item_lists
  has_many :images
  has_many :ordered_items
  has_many :dimentions
  has_many :carts, through: :item_lists
  has_many :cart_records, through: :item_lists
  has_many :favorite_items, through: :item_lists
  belongs_to :shop
  belongs_to :brand
  belongs_to :gender
  belongs_to :category
end

app/models/item_list.rb
class ItemList < ApplicationRecord
  belongs_to :item
  belongs_to :size
  belongs_to :color
  has_many :carts
  has_many :cart_records
  has_many :favorite_items
  has_many :users, through: :carts
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :ordered_items, dependent: :destroy
  has_many :items, through: :ordered_items
  belongs_to :address_list

  accepts_nested_attributes_for :ordered_items, allow_destroy: true
end

app/models/order_history.rb
class OrderHistory < ApplicationRecord
  has_many :ordered_items
  belongs_to :order
  belongs_to :shipping_status
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order_history
  belongs_to :item
  belongs_to :color
  belongs_to :size
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/shipment.rb
class Shipment < ApplicationRecord
end

app/models/shipping_status.rb
class ShippingStatus < ApplicationRecord
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :items
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :carts
  has_many :item_lists
  has_many :items, through: :item_lists
  has_many :ordered_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :address_lists, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :cart_records
  has_many :item_lists, through: :carts
  has_many :favorite_items, dependent: :destroy
  has_many :favorite_shops, dependent: :destroy
  has_many :favorite_brands, dependent: :destroy
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.includes([:shop, :brand, :gender, :category, :images])
    # チェック済商品を画面表示
    @checked_items = Item.where(id: session[:checked_item_ids])
  end

  def show
    # チェックした商品をsessionに保存し、チェック済商品を画面表示できるようにする
    # sessionがない場合は初期化
    session[:checked_item_ids] = session[:checked_item_ids].present? ? session[:checked_item_ids] : []
    # sessionにチェックした商品IDを保存
    session[:checked_item_ids] << params[:id]
    @checked_items = Item.where(id: session[:checked_item_ids])
    @item = Item.find(params[:id])
    @list = @item.item_lists
  end

  def detail_search
  end

  # 検索パラメータの有無に応じて動的にSQL組み換えて検索実行
  def detail_search_result
    # 画面から検索パラメータを取得
    search_param_keyword = params[:detail_search][:keyword]
    search_param_brand = params[:detail_search][:brand]
    search_param_shop = params[:detail_search][:shop]
    # 検索パラメータによらないSQLの共通部分
    sql = "select i.id from items i inner join brands b on i.brand_id = b.id inner join shops s on i.shop_id = s.id where 1 = 1 "
    # 検索パラメータの有無に応じて動的にSQL組み換え
    # バインドパラメータ（hash形式）も同時に動的作成
    bind_params_hash = {}
    if search_param_keyword.present?
      sql << "and i.name like :search_param_keyword "
      bind_params_hash[:search_param_keyword] = '%' +search_param_keyword + '%'
    end
    if search_param_brand.present?
      sql << "and b.name like :search_param_brand "
      bind_params_hash[:search_param_brand] = '%' +search_param_brand + '%'
    end
    if search_param_shop.present?
      sql << "and s.name like :search_param_shop "
      bind_params_hash[:search_param_shop] = '%' +search_param_shop + '%'
    end
    # SQL生成
    sanitize_sql_array = []
    sanitize_sql_array << sql
    sanitize_sql_array << bind_params_hash
    exe_sql = ActiveRecord::Base.send(
      :sanitize_sql_array,
      sanitize_sql_array
    )
    # SQL実行
    con = ActiveRecord::Base.connection
    result = con.select_all(exe_sql)
    # viewに詰めるためのパラメータを作成
    item_id_array = []
    result.to_hash.each do |result_hash|
      item_id_array << result_hash["id"]
    end
    @items = Item.where("id IN (?)", item_id_array)
    # チェック済商品を画面表示用
    @checked_items = Item.where(id: session[:checked_item_ids])
    render 'index'
  end

  def search
    @search_items = Item.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def searchResult
    @search_items_result = Item.find(params[:id])
    respond_to do |format|
      format.html
      # アクション名を指定する方法ではjbuilderが読み込まれなかったため、下記の表記にしています。
      format.json {render 'searchResult.json.jbuilder' }
    end
  end

end

app/views/items/_item.html.haml
%li
  .listInner.clearfix
    .photo{'data-item-id': item.id}
      = link_to item_path(item) do
        = image_tag(item.images.first.image_url,alt: item.description,width:"171",height:"205")
        .feed-tag-group
          .feed-tag-group-item
            %span.feed-tag.feed-tag-coupon.coupon_C3 ¥3,000クーポン
    %p.label
      = item.name
    %p.price.discount
      = item.proposed_price
      %span.tax 税込
      %span.off (49%OFF)

app/views/items/detail_search.html.haml
#wrapper
  #gblHeaderStuck
    .header#gblHeader
      #hWrapper
        #hWrapperInner
          #header.clearfix
            .clearfix#hHeader
              %h1#hLogo
                = link_to "ZOZOTOWN", "http://zozo.jp/"
              #hItemSearch.clearfix
                %form{action:"/search", method:"get", name:"keyword"}
                  %p#hKeyword
                    %input#searchText.def{type:"text",name:"p_keyv",placeholder:"何かお探しですか？",autocomplete:"off"}
                  %p#hSubmit.hBtn
                    %input{title:"検索",type:"submit"}
            .clearfix#hCtrl
              %ul.clearfix#hCtrlList
                %li.hPopWrap.static#hUserName
                  %p#hThumbs
                    %span#hName
                      %span.userName.textTruncate ああああ様
                %li.hPopWrap.static#hNotice
                  = link_to "/notice/" do
                    %span.ico.ico_notice
                      %span 通知機能
                %li#hFavoriteLink.static.hPopWrap
                  = link_to "/_member/favoritelist/" do
                    %span#hFavorite.ico.ico_favorite
                      %span お気に入り
                %li#hCart
                  %span.clearfix
                    = link_to "/carts" do
                      %span.ico.ico_cart
                        %span カート
                %li#hServiceMap.static.hPopWrap
                  %span.ico.ico_siteMap
                    %span サイトマップ
  .detail-search
    %h1 こだわり検索
    = form_tag('detail_search_result', method: "GET", class: "detail-search-form") do
      %p 検索条件を指定してください。全項目に条件を指定しなくても検索できます。
      %table
        %tbody
          %tr
            %th
              = label_tag(:keyword, "キーワード")
            %td
              = text_field_tag 'detail_search[keyword]'
          %tr
            %th
              = label_tag(:brand, "ブランド")
            %td
              = text_field_tag 'detail_search[brand]'
          %tr
            %th
              = label_tag(:shop, "ショップ")
            %td
              = text_field_tag 'detail_search[shop]'
      = submit_tag "検索する"